
import __ASTRO_IMAGE_IMPORT_Bv9GN from "../../../src/data/figures/vaccine_directional_changes.png?astroContentImageFlag=&importer=src%2Fcollections%2Fposts%2Fwearables_vaccine.md";
import __ASTRO_IMAGE_IMPORT_1hO3My from "../../../src/data/figures/fever_fig.png?astroContentImageFlag=&importer=src%2Fcollections%2Fposts%2Ffever_detection.md";
import __ASTRO_IMAGE_IMPORT_18GHAj from "./fujifilm_xt50/web/DSCF0306.JPG?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FFujifilm_xt50.yml";
import __ASTRO_IMAGE_IMPORT_YaQ4m from "./fujifilm_200_1/ferris_sd.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FFujifilm_200_1.yml";
import __ASTRO_IMAGE_IMPORT_14If48 from "./cinestill_800t/chandelier.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FCinestill_800T.yml";
import __ASTRO_IMAGE_IMPORT_1pnF56 from "./portra_400_1/backlit_amelia_coronado.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FPortra_400_1.yml";
import __ASTRO_IMAGE_IMPORT_ZzWTNd from "./unknown/sunset_anza.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FUnknown.yml";
import __ASTRO_IMAGE_IMPORT_Z1crGhE from "./portra_400_2/kings_canyon_sunset.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FPortra_400_2.yml";
import __ASTRO_IMAGE_IMPORT_1lTBAQ from "./fujifilm_200_2/glider_port.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FFujifilm_200_2.yml";
import __ASTRO_IMAGE_IMPORT_2toGm1 from "./ilford_delta_3200/album_cover.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FIlford_delta_3200.yml";
export default new Map([["../../../src/data/figures/vaccine_directional_changes.png?astroContentImageFlag=&importer=src%2Fcollections%2Fposts%2Fwearables_vaccine.md", __ASTRO_IMAGE_IMPORT_Bv9GN], ["../../../src/data/figures/fever_fig.png?astroContentImageFlag=&importer=src%2Fcollections%2Fposts%2Ffever_detection.md", __ASTRO_IMAGE_IMPORT_1hO3My], ["./fujifilm_xt50/web/DSCF0306.JPG?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FFujifilm_xt50.yml", __ASTRO_IMAGE_IMPORT_18GHAj], ["./fujifilm_200_1/ferris_sd.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FFujifilm_200_1.yml", __ASTRO_IMAGE_IMPORT_YaQ4m], ["./cinestill_800t/chandelier.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FCinestill_800T.yml", __ASTRO_IMAGE_IMPORT_14If48], ["./portra_400_1/backlit_amelia_coronado.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FPortra_400_1.yml", __ASTRO_IMAGE_IMPORT_1pnF56], ["./unknown/sunset_anza.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FUnknown.yml", __ASTRO_IMAGE_IMPORT_ZzWTNd], ["./portra_400_2/kings_canyon_sunset.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FPortra_400_2.yml", __ASTRO_IMAGE_IMPORT_Z1crGhE], ["./fujifilm_200_2/glider_port.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FFujifilm_200_2.yml", __ASTRO_IMAGE_IMPORT_1lTBAQ], ["./ilford_delta_3200/album_cover.jpg?astroContentImageFlag=&importer=src%2Fcollections%2Falbums%2FIlford_delta_3200.yml", __ASTRO_IMAGE_IMPORT_2toGm1]]);
		